AmoabaKelvin/ishortn.ink

- src/app/[shortenedLink]/page.tsx
- src/app/api/links/route.ts
```
[Error]: Headers cannot be modified. Read more: https://nextjs.org/docs/app/api-reference/functions/headers
```
> Fixed Error with Vercel when passing request headers

- src/app/api/[[...route]]/dynamic-links.ts
do not use the logic from the dynamic links form action to create the dynamic links due to a prisma `upsert` issue.
> Refactor dynamic links API to not use server action function

- src/components/dashboard/navigation-bar.tsx
> fix: resolved issue #70

- emails/welcome-email.tsx
- src/components/dashboard/link-overview/link-showcase.tsx
Added conditional check for null name in which case mail goes with "Hi there"
Closes #98
> Mail recipient's name null check

- src/app/(main)/dashboard/analytics/[alias]/_components/bar-chart.tsx
- src/app/(main)/dashboard/analytics/[alias]/page.tsx
- src/app/(main)/dashboard/qrcodes/upgrade-text.tsx
- src/server/api/routers/link/link.service.ts
- Optimize getLinkVisits query to filter by date for free users
- Add isProUser flag to API response
- Update frontend to show limited data message for free users
> feat(analytics): Limit free users to 7 days of data

- src/app/(main)/dashboard/qrcodes/utils.ts
- src/server/api/routers/qrcode/qrcode.service.ts
- The code changes update the QR code creation limit from 3 to 5.
> fix: do not disable create qrcode button when user can create one

- src/app/(main)/dashboard/analytics/[alias]/page.tsx
- src/app/(main)/dashboard/analytics/[alias]/range-selector-wrapper.tsx
- src/app/(main)/dashboard/analytics/[alias]/range-selector.tsx
- src/components/ui/select.tsx
- src/server/api/routers/link/link.input.ts
- src/server/api/routers/link/link.procedure.ts
- src/server/api/routers/link/link.service.ts
This commit enhances the link analytics feature by allowing users to
filter data by different time periods.
> Add date range filter to link analytics

- src/app/(main)/[linkAlias]/link-preview.tsx
- src/app/(main)/[linkAlias]/page.tsx
- src/app/(main)/dashboard/analytics/[alias]/page.tsx
- src/app/api/v1/links/route.ts
- src/server/api/routers/link/link.service.ts
users will now be able to see the site that the shortened link points to if they append ! to the url.
This is a way to help improve security of the links when sharing
> feat: add link previews

- drizzle/0017_left_scorpion.sql
- drizzle/meta/0017_snapshot.json
- drizzle/meta/_journal.json
- src/app/(main)/analytics/[alias]/page.tsx
- src/app/(main)/dashboard/analytics/[alias]/_components/bar-list.tsx
- src/app/(main)/dashboard/analytics/[alias]/countries-and-cities-stats.tsx
- src/app/(main)/dashboard/analytics/[alias]/page.tsx
- src/lib/constants.ts
- src/lib/core/analytics/index.ts
- src/server/api/routers/link/link.service.ts
- src/server/db/schema.ts
- **feat(db): add continent column to LinkVisit table**
- **refactor(api): improve code formatting**
- **feat(analytics): add `continents` field in analytics**
> add continents in analytics

- .gitignore
- drizzle/0018_gray_captain_midlands.sql
- drizzle/meta/0018_snapshot.json
- drizzle/meta/_journal.json
- package.json
- src/app/(main)/dashboard/_components/single-link/link-card.tsx
- src/app/(main)/dashboard/_components/single-link/update-link-modal.tsx
- src/app/(main)/dashboard/link/new/page.tsx
- src/lib/core/cache/index.ts
- src/server/api/routers/link/link.input.ts
- src/server/api/routers/link/link.service.ts
- src/server/db/schema.ts
- **chore: add db:production:migrate script to package.json**
- **chore: add .env.prod to .gitignore**
- **feat: Add 'name' column to 'Link' table**
- **feat: Add 'name' field to link creation and update**
> add user provided link names when creating or updating links

- next.txt
- src/lib/core/cache/index.ts
- src/server/api/routers/link/link.service.ts
- src/server/api/routers/link/utils.ts
- **chore: remove unnecessary files**
- **refactor: Refactor cache implementation and improve link resolution service**
> rewrite caching layer

- drizzle/0019_tiresome_boomerang.sql
- drizzle/meta/0019_snapshot.json
- drizzle/meta/_journal.json
- src/app/(main)/dashboard/_components/dashboard-nav.tsx
- src/app/(main)/dashboard/_components/sidebar/quick-link-shortening-form.tsx
- src/app/(main)/dashboard/_components/tab-switcher.tsx
- src/app/(main)/dashboard/qrcodes/create/page.tsx
- src/app/(main)/dashboard/settings/billing/billing.tsx
- src/app/(main)/dashboard/settings/domains/domains.tsx
- src/app/(main)/dashboard/settings/domains/page.tsx
- src/app/(main)/dashboard/settings/general/page.tsx
- src/app/(main)/dashboard/settings/general/settings-form.tsx
- src/app/(main)/dashboard/settings/layout.tsx
- src/server/api/root.ts
- src/server/api/routers/link/link.service.ts
- src/server/api/routers/settings/settings.input.ts
- src/server/api/routers/settings/settings.procedure.ts
- src/server/api/routers/settings/settings.service.ts
- src/server/db/schema.ts
- **feat(database): add SiteSettings table and update schema with relations**
- **feat(settings): add schema for updating site settings**
- **feat(settings): implement get and update functions for site settings**
- **feat(settings): add TRPC router for getting and updating site settings**
- **feat(link): use user-specified default domain when shortening**
- **feat(api): add site settings router to the main application router**
- **feat(settings): add settings form for selecting default domain**
- **style: improve layout and formatting for better readability**
- **fix(tab-switcher): update settings link to point to general settings**
- **refactor(domains): remove console log and improve conditional rendering**
- **feat(qrcodes): add error handling for link shortening**
- …
> add site settings

- drizzle/0020_whole_manta.sql
- drizzle/meta/0020_snapshot.json
- drizzle/meta/_journal.json
- package.json
- src/app/(main)/dashboard/_components/dashboard-sidebar.tsx
- src/app/(main)/dashboard/_components/sidebar/monthly-usage.tsx
- src/app/(main)/dashboard/_components/sidebar/quick-link-shortening-form.tsx
- src/app/(main)/dashboard/_components/sidebar/user-links-overview.tsx
- src/app/(main)/dashboard/_components/single-link/link-card.tsx
- src/app/(main)/dashboard/page.tsx
- src/components/ui/progress.tsx
- src/lib/core/cache/index.ts
- src/server/api/routers/link/link.service.ts
- src/server/api/routers/link/utils.ts
- src/server/api/routers/settings/settings.service.ts
- src/server/api/trpc.ts
- src/server/db/schema.ts
- **chore: add @radix-ui/react-progress package**
- **feat(database): add monthlyLinkCount and lastLinkCountReset fields to User table**
- **feat(cache): export redis instance for external usage**
- **feat(progress): add Progress component using Radix UI**
- **feat(dashboard): add MonthlyUsage component to display monthly link usage**
- **style(dashboard): refactor components to use Card for improved layout**
- **feat(link): add monthly link creation limit**
- **feat(link): implement monthly link creation limit and alias validation**
- **refactor(trpc): clean up comments and enhance context types for better clarity**
- **feat(dashboard): optimize data fetching by using Promise.all for links and user subscription**
- **refactor: remove debug logging for cached domain retrieval**
> monthly limits

- src/app/(main)/dashboard/link/new/upgrade-to-pro-ai-tooltip.tsx
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
> fix: improve AI tooltip interaction and styling

- src/middlewares/record-click.ts
This fixes a bug where visits were only being counted as unique per IP,
regardless of which link was being visited.
> fix(analytics): ensure unique visits are counted per link and IP

- drizzle/0021_smiling_juggernaut.sql
- drizzle/0022_same_doctor_spectrum.sql
- drizzle/0023_unusual_kree.sql
- drizzle/0024_lethal_lady_vermin.sql
- drizzle/meta/0022_snapshot.json
- drizzle/meta/0023_snapshot.json
- drizzle/meta/0024_snapshot.json
- drizzle/meta/_journal.json
- src/app/(main)/dashboard/_components/all-links-renderer.tsx
- src/app/(main)/dashboard/_components/sidebar/quick-link-shortening-form.tsx
- src/app/(main)/dashboard/_components/single-link/link-card.tsx
- src/app/(main)/dashboard/_components/single-link/update-link-modal.tsx
- src/app/(main)/dashboard/link/new/page.tsx
- src/app/(main)/dashboard/page.tsx
- src/app/(main)/dashboard/qrcodes/qrcode-card.tsx
- src/lib/core/cache/index.ts
- src/server/api/root.ts
- src/server/api/routers/link/link.input.ts
- src/server/api/routers/link/link.service.ts
- src/server/api/routers/tag/tag.router.ts
- src/server/api/routers/tag/tag.service.ts
- src/server/db/schema.ts
allows users to add tags to their links and filter by those tags.
> feat: link tagging feature

- src/app/(main)/dashboard/_components/single-link/update-link-modal.tsx
- Add collapsible sections for Basic Information, Tags, and Optional Settings
- Implement smooth animations using Framer Motion for section expansions
- Enhance user experience by organizing link editing form into logical, expandable groups
> refactor: improve link editing UX with collapsible sections

- drizzle/0025_sudden_expediter.sql
- drizzle/meta/0025_snapshot.json
- drizzle/meta/_journal.json
- package.json
- src/app/(main)/dashboard/_components/all-links-renderer.tsx
- src/app/(main)/dashboard/_components/single-link/link-actions.tsx
- src/app/(main)/dashboard/page.tsx
- src/components/ui/select.tsx
- src/lib/core/cache/index.ts
- src/middleware.ts
- src/server/api/routers/link/link.input.ts
- src/server/api/routers/link/link.procedure.ts
- src/server/api/routers/link/link.service.ts
- src/server/db/schema.ts
- **chore: update @radix-ui/react-select dependency to version 2.1.7**
- **refactor: enhance middleware logic for pathname handling**
- **feat: add archived field to link schema for better data management**
- **feat: implement link archiving functionality**
- **feat: add toggleArchive mutation to link router**
- **feat: enhance link input schema with geolocation and pagination constraints**
- **refactor: update Select component styles and functionality**
- **feat: implement link archiving actions in LinkActions component**
- **feat: add archived filter functionality to links renderer**
- **feat: include archivedFilter in DashboardPage for enhanced link management**
- **feat: add archived column to Link table and update journal and snapshot**
> Archiving Links

- src/app/api/v1/links/[alias]/route.ts
- **feat: add PATCH endpoint for updating links with validation**
- **feat: enhance error handling in PATCH endpoint for link updates**
> add patch endpoint to api

- src/app/(main)/verify-password/[linkId]/page.tsx
- src/app/api/link/route.ts
- src/lib/core/analytics/index.ts
- src/middlewares/record-click.ts
- Create dedicated password verification page at /verify-password/[linkId]
- Redirect password-protected links to verification page instead of showing error
- Fix null IP address handling in analytics for local development
- Eliminates duplicate API calls for password verification
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
> Fix password-protected link redirection
